name: Artifacts Download
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a Code
        run: echo "${{ toJSON(github) }}" >> ArtifactsDemo.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ArtifactsDemo
          path: ArtifactsDemo.txt
