name: Output Checks
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_file: ${{ steps.publish.outputs.afilemame }}
    steps:
      - name: Generate a Code
        run: echo "${{ toJSON(github) }}" >> "ArtifactsDemo_S(date"+%m%d%y").txt"
      - name: Output Extract
        id: publish
        run: ls ArtifactsDemo*.txt echo 'afilemame={}' >> $GITHUB_OUTPUT ';'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Filename
        run: echo "${{ needs.build.outputs.artifact_file }}"
    
